In [1]:
import pandas as pd
import numpy as np

### Marco muestral 2005

In [2]:
#datos 2019, 2020, 2021

t05_19_21_j = pd.read_excel("G:/Unidades compartidas/Mercado laboral/Datos/1_Raw/Datos_marco_2005_proyecciones_2018.xlsx",     
                       sheet_name = "jovenes", header = 0,
                       nrows = 34,  usecols = "A, B, D:H, J, K")
t05_19_21_j

,periodo,trimestre,PET,FT,desocupados,ocupados,informal_dane,TO,TD
0,2019,1 ene-mar,1.906859e+06,1.312070e+06,281993.018514,1.030077e+06,307095.522602,0.540196,0.214922
1,2019,2 feb-abr,1.886081e+06,1.255149e+06,247854.835334,1.007294e+06,334128.259464,0.534067,0.197470
2,2019,3 mar-may,1.873743e+06,1.238067e+06,230348.063765,1.007719e+06,328825.067613,0.537811,0.186055
3,2019,4 abr-jun,1.852806e+06,1.226260e+06,225068.323063,1.001191e+06,341323.923708,0.540365,0.183540
4,2019,5 may-jul,1.860595e+06,1.272693e+06,229032.494687,1.043660e+06,324509.039302,0.560928,0.179959
5,2019,6 jun-ago,1.817007e+06,1.201007e+06,210778.044044,9.902289e+05,286754.111979,0.544978,0.175501
6,2019,7 jul-sep,1.873058e+06,1.228250e+06,191728.500875,1.036521e+06,288222.692213,0.553384,0.156099
7,2019,8 ago-oct,1.881305e+06,1.220396e+06,190116.575643,1.030279e+06,282461.438035,0.547641,0.155783
8,2019,9 sep-nov,1.904701e+06,1.268448e+06,199004.802918,1.069443e+06,324035.712900,0.561475,0.156888
9,2019,91 oct-dic,1.836078e+06,1.240895e+06,220813.288327,1.020082e+06,328803.242823,0.555577,0.177947
10,2019,92 nov19-ene20,1.829273e+06,1.221886e+06,238752.845284,9.831336e+05,313370.340052,0.537445,0.195397
11,2019,93 dic19-feb20,1.834508e+06,1.207716e+06,241706.025692,9.660100e+05,304062.419465,0.526577,0.200135
12,2020,1 ene-mar,1.856186e+06,1.182543e+06,242781.776442,9.397617e+05,464812.135136,0.506286,0.205305
13,2020,2 feb-abr,1.854519e+06,1.073721e+06,246027.664699,8.276935e+05,565483.636002,0.446312,0.229136
14,2020,3 mar-may,1.832082e+06,1.031959e+06,285873.724245,7.460849e+05,525141.425038,0.407233,0.277021
15,2020,4 abr-jun,1.858879e+06,1.065203e+06,350244.016193,7.149591e+05,329753.362247,0.384618,0.328805
16,2020,5 may-jul,1.855527e+06,1.152163e+06,393453.041571,7.587100e+05,227306.198964,0.408892,0.341491
17,2020,6 jun-ago,1.885674e+06,1.215103e+06,406415.144764,8.086874e+05,249595.617149,0.428859,0.334470
18,2020,7 jul-sep,1.880515e+06,1.227460e+06,377889.797151,8.495705e+05,273903.450365,0.451775,0.307863
19,2020,8 ago-oct,1.900708e+06,1.268411e+06,352727.313414,9.156835e+05,296935.473600,0.481759,0.278086
20,2020,9 sep-nov,1.886046e+06,1.271829e+06,324051.623466,9.477770e+05,313840.989144,0.502521,0.254792
21,2020,91 oct-dic,1.865190e+06,1.252786e+06,310470.022026,9.423164e+05,309357.349352,0.505212,0.247824
22,2020,92 nov20-ene21,1.850030e+06,1.234182e+06,332303.470645,9.018788e+05,296739.458917,0.487494,0.269250
23,2020,93 dic20-feb21,1.871922e+06,1.261522e+06,372401.798233,8.891204e+05,287397.956498,0.474977,0.295200
24,2021,1 ene-mar,1.881533e+06,1.278243e+06,379639.413575,8.986040e+05,297174.588474,0.477591,0.297001
25,2021,2 feb-abr,1.864650e+06,1.265693e+06,348790.783616,9.169019e+05,304810.289868,0.491729,0.275573
26,2021,3 mar-may,1.870196e+06,1.253238e+06,324115.791281,9.291221e+05,335514.788306,0.496805,0.258623
27,2021,4 abr-jun,1.896257e+06,1.238299e+06,305615.008878,9.326838e+05,327524.483963,0.491855,0.246802
28,2021,5 may-jul,1.908575e+06,1.260298e+06,298690.468490,9.616075e+05,325849.832541,0.503835,0.237000
29,2021,6 jun-ago,1.881531e+06,1.220753e+06,277384.743576,9.433684e+05,292242.029276,0.501383,0.227224
30,2021,7 jul-sep,1.853844e+06,1.208472e+06,264794.090772,9.436782e+05,288091.038043,0.509039,0.219115
31,2021,8 ago-oct,1.872673e+06,1.233336e+06,235864.778146,9.974708e+05,293957.538264,0.532645,0.191241
32,2021,9 sep-nov,1.870979e+06,1.212241e+06,219226.146650,9.930146e+05,306085.245631,0.530746,0.180844
33,2021,91 oct-dic,1.874526e+06,1.185686e+06,198069.246535,9.876163e+05,317652.184115,0.526862,0.167050

In [3]:
t05_19_21_nj = pd.read_excel("G:/Unidades compartidas/Mercado laboral/Datos/1_Raw/Datos_marco_2005_proyecciones_2018.xlsx",     
                       sheet_name = "no jovenes", header = 0,
                       nrows = 34,  usecols = "A, B, D:H, J, K")

#### Marge

In [4]:
t05_19_21_j.columns

Index(['periodo', 'trimestre', 'PET', 'FT', 'desocupados', 'ocupados',
       'informal_dane', 'TO', 'TD'],
      dtype='object')

In [5]:
##renombrar variables hombres
t05_19_21_j.rename(columns = {'periodo': 'Periodo', 'trimestre': "Trimestre", 'PET':'PET_j', 
                               'FT':'FT_j', 'desocupados': 'Desocupados_j','ocupados': 'Ocupados_j',
                              'informal_dane':'Informal_j', 'TO': 'TO_j', 'TD':'TD_j'},
               inplace = True)
##renombrar variables mujeres
t05_19_21_nj.rename(columns = {'periodo': 'Periodo', 'trimestre': "Trimestre", 'PET':'PET_nj', 
                               'FT':'FT_nj', 'desocupados': 'Desocupados_nj','ocupados': 'Ocupados_nj',
                              'informal_dane':'Informal_nj', 'TO': 'TO_nj', 'TD':'TD_nj'},
               inplace = True)

In [6]:
t05_19_21_nj.columns

Index(['Periodo', 'Trimestre', 'PET_nj', 'FT_nj', 'Desocupados_nj',
       'Ocupados_nj', 'Informal_nj', 'TO_nj', 'TD_nj'],
      dtype='object')

In [7]:
#merge
t05_19_21_j_nj = pd.merge(left=t05_19_21_j, right=t05_19_21_nj, 
                            on = ["Periodo", "Trimestre"], how = 'inner', sort =False,
                            validate = '1:1', suffixes=("_hombre", "_mujer"))
#quitar los numeros de la columna trimestre
t05_19_21_j_nj["Trimestre"] = (pd.Series(t05_19_21_j_nj["Trimestre"], # r'\d\s', \A coincide al inciio , \b                                
                                         dtype = "string").str.split( r'\d\s', expand = True).get(1))
t05_19_21_j_nj

,Periodo,Trimestre,PET_j,FT_j,Desocupados_j,Ocupados_j,Informal_j,TO_j,TD_j,PET_nj,FT_nj,Desocupados_nj,Ocupados_nj,Informal_nj,TO_nj,TD_nj
0,2019,ene-mar,1.906859e+06,1.312070e+06,281993.018514,1.030077e+06,307095.522602,0.540196,0.214922,4.147007e+06,3.118140e+06,293075.990621,2.825064e+06,1.183310e+06,0.681230,0.093991
1,2019,feb-abr,1.886081e+06,1.255149e+06,247854.835334,1.007294e+06,334128.259464,0.534067,0.197470,4.181993e+06,3.157840e+06,266801.138326,2.891039e+06,1.251588e+06,0.691307,0.084488
2,2019,mar-may,1.873743e+06,1.238067e+06,230348.063765,1.007719e+06,328825.067613,0.537811,0.186055,4.208299e+06,3.190764e+06,246244.403659,2.944520e+06,1.315927e+06,0.699694,0.077174
3,2019,abr-jun,1.852806e+06,1.226260e+06,225068.323063,1.001191e+06,341323.923708,0.540365,0.183540,4.243486e+06,3.211599e+06,219990.331461,2.991609e+06,1.314769e+06,0.704988,0.068499
4,2019,may-jul,1.860595e+06,1.272693e+06,229032.494687,1.043660e+06,324509.039302,0.560928,0.179959,4.249496e+06,3.229738e+06,226167.538644,3.003571e+06,1.316920e+06,0.706806,0.070027
5,2019,jun-ago,1.817007e+06,1.201007e+06,210778.044044,9.902289e+05,286754.111979,0.544978,0.175501,4.306652e+06,3.248356e+06,239261.612068,3.009094e+06,1.279772e+06,0.698708,0.073656
6,2019,jul-sep,1.873058e+06,1.228250e+06,191728.500875,1.036521e+06,288222.692213,0.553384,0.156099,4.263744e+06,3.206420e+06,248722.633325,2.957697e+06,1.272215e+06,0.693686,0.077570
7,2019,ago-oct,1.881305e+06,1.220396e+06,190116.575643,1.030279e+06,282461.438035,0.547641,0.155783,4.268243e+06,3.202075e+06,243059.447334,2.959015e+06,1.271714e+06,0.693263,0.075907
8,2019,sep-nov,1.904701e+06,1.268448e+06,199004.802918,1.069443e+06,324035.712900,0.561475,0.156888,4.257217e+06,3.220642e+06,220499.243496,3.000142e+06,1.329629e+06,0.704719,0.068464
9,2019,oct-dic,1.836078e+06,1.240895e+06,220813.288327,1.020082e+06,328803.242823,0.555577,0.177947,4.337751e+06,3.249759e+06,205538.280922,3.044221e+06,1.348845e+06,0.701797,0.063247
10,2019,nov19-ene20,1.829273e+06,1.221886e+06,238752.845284,9.831336e+05,313370.340052,0.537445,0.195397,4.356308e+06,3.265968e+06,229659.566734,3.036309e+06,1.334281e+06,0.696991,0.070319
11,2019,dic19-feb20,1.834508e+06,1.207716e+06,241706.025692,9.660100e+05,304062.419465,0.526577,0.200135,4.362571e+06,3.264745e+06,240756.820043,3.023988e+06,1.339247e+06,0.693166,0.073744
12,2020,ene-mar,1.856186e+06,1.182543e+06,242781.776442,9.397617e+05,464812.135136,0.506286,0.205305,4.352063e+06,3.162553e+06,270387.961760,2.892165e+06,1.660498e+06,0.664550,0.085497
13,2020,feb-abr,1.854519e+06,1.073721e+06,246027.664699,8.276935e+05,565483.636002,0.446312,0.229136,4.364724e+06,2.951418e+06,338727.632497,2.612691e+06,1.873429e+06,0.598592,0.114768
14,2020,mar-may,1.832082e+06,1.031959e+06,285873.724245,7.460849e+05,525141.425038,0.407233,0.277021,4.397904e+06,2.855299e+06,458429.300190,2.396869e+06,1.766597e+06,0.545003,0.160554
15,2020,abr-jun,1.858879e+06,1.065203e+06,350244.016193,7.149591e+05,329753.362247,0.384618,0.328805,4.381994e+06,2.823207e+06,561645.995049,2.261561e+06,1.280533e+06,0.516103,0.198939
16,2020,may-jul,1.855527e+06,1.152163e+06,393453.041571,7.587100e+05,227306.198964,0.408892,0.341491,4.395693e+06,2.973134e+06,636849.235552,2.336284e+06,9.817524e+05,0.531494,0.214201
17,2020,jun-ago,1.885674e+06,1.215103e+06,406415.144764,8.086874e+05,249595.617149,0.428859,0.334470,4.375227e+06,2.984216e+06,596218.977767,2.387997e+06,9.906021e+05,0.545800,0.199791
18,2020,jul-sep,1.880515e+06,1.227460e+06,377889.797151,8.495705e+05,273903.450365,0.451775,0.307863,4.389292e+06,3.075950e+06,558172.971433,2.517777e+06,1.101448e+06,0.573618,0.181464
19,2020,ago-oct,1.900708e+06,1.268411e+06,352727.313414,9.156835e+05,296935.473600,0.481759,0.278086,4.377614e+06,3.114604e+06,468365.137018,2.646239e+06,1.166855e+06,0.604494,0.150377
20,2020,sep-nov,1.886046e+06,1.271829e+06,324051.623466,9.477770e+05,313840.989144,0.502521,0.254792,4.400744e+06,3.181250e+06,426356.283459,2.754894e+06,1.220450e+06,0.626006,0.134022
21,2020,oct-dic,1.865190e+06,1.252786e+06,310470.022026,9.423164e+05,309357.349352,0.505212,0.247824,4.429912e+06,3.210708e+06,397461.490477,2.813246e+06,1.248653e+06,0.635057,0.123792
22,2020,nov20-ene21,1.850030e+06,1.234182e+06,332303.470645,9.018788e+05,296739.458917,0.487494,0.269250,4.453393e+06,3.205977e+06,430261.387679,2.775715e+06,1.248092e+06,0.623281,0.134206
23,2020,dic20-feb21,1.871922e+06,1.261522e+06,372401.798233,8.891204e+05,287397.956498,0.474977,0.295200,4.439717e+06,3.202589e+06,476223.704175,2.726366e+06,1.225384e+06,0.614085,0.148700
24,2021,ene-mar,1.881533e+06,1.278243e+06,379639.413575,8.986040e+05,297174.588474,0.477591,0.297001,4.438034e+06,3.202960e+06,499360.919329,2.703599e+06,1.201696e+06,0.609188,0.155906
25,2021,feb-abr,1.864650e+06,1.265693e+06,348790.783616,9.169019e+05,304810.289868,0.491729,0.275573,4.462707e+06,3.195455e+06,486109.724207,2.709346e+06,1.179433e+06,0.607108,0.152125
26,2021,mar-may,1.870196e+06,1.253238e+06,324115.791281,9.291221e+05,335514.788306,0.496805,0.258623,4.464713e+06,3.178407e+06,461145.956597,2.717261e+06,1.167860e+06,0.608608,0.145087
27,2021,abr-jun,1.896257e+06,1.238299e+06,305615.008878,9.326838e+05,327524.483963,0.491855,0.246802,4.446287e+06,3.130513e+06,466112.328194,2.664400e+06,1.161811e+06,0.599242,0.148893
28,2021,may-jul,1.908575e+06,1.260298e+06,298690.468490,9.616075e+05,325849.832541,0.503835,0.237000,4.441333e+06,3.164845e+06,439126.892435,2.725718e+06,1.176891e+06,0.613716,0.138751
29,2021,jun-ago,1.881531e+06,1.220753e+06,277384.743576,9.433684e+05,292242.029276,0.501383,0.227224,4.475617e+06,3.190815e+06,409014.326944,2.781801e+06,1.200391e+06,0.621546,0.128185
30,2021,jul-sep,1.853844e+06,1.208472e+06,264794.090772,9.436782e+05,288091.038043,0.509039,0.219115,4.510338e+06,3.239478e+06,361908.126026,2.877570e+06,1.240226e+06,0.637994,0.111718
31,2021,ago-oct,1.872673e+06,1.233336e+06,235864.778146,9.974708e+05,293957.538264,0.532645,0.191241,4.498358e+06,3.216486e+06,331357.126096,2.885128e+06,1.274441e+06,0.641374,0.103018
32,2021,sep-nov,1.870979e+06,1.212241e+06,219226.146650,9.930146e+05,306085.245631,0.530746,0.180844,4.506728e+06,3.187335e+06,309151.509207,2.878183e+06,1.275352e+06,0.638641,0.096994
33,2021,oct-dic,1.874526e+06,1.185686e+06,198069.246535,9.876163e+05,317652.184115,0.526862,0.167050,4.509639e+06,3.103748e+06,266058.965700,2.837689e+06,1.271011e+06,0.629250,0.085722

In [8]:
# fragmentar bases para imputar sencillo
#2019
m_19 = t05_19_21_j_nj["Periodo"] == 2019
t05_19t = t05_19_21_j_nj[m_19==True]
t05_19t.reset_index(drop =True, inplace = True)
#2020
m_20 = t05_19_21_j_nj["Periodo"] == 2020
t05_20t = t05_19_21_j_nj[m_20==True]
t05_20t.reset_index(drop =True, inplace = True)
#2021
m_21 = t05_19_21_j_nj["Periodo"] == 2021
t05_21t = t05_19_21_j_nj[m_21==True]
t05_21t.reset_index(drop =True, inplace = True)

### Marco muestral 2018

In [9]:
#datos 2021
names_col_21= ["Poblaciones", "Ene - Mar","Feb - Abr", "Mar - May","Abr - Jun", "May - Jul",
             "Jun - Ago", "Jul - Sep", "Ago - Oct", "Sep - Nov", "Oct - Dic","Nov 21 - Ene 22", 
             "Dic 21 - Feb 22"]
t18_21_j = pd.read_excel("G:/Unidades compartidas/Mercado laboral/Datos/1_Raw/anexo_GEIH_juventud_abr22_jun22.xls",     
                       sheet_name = "23 áreas trim movil", header = 0,
                       skiprows = range(31), nrows = 11, usecols = "A:M", names =names_col_21)
t18_21_j

,Poblaciones,Ene - Mar,Feb - Abr,Mar - May,Abr - Jun,May - Jul,Jun - Ago,Jul - Sep,Ago - Oct,Sep - Nov,Oct - Dic,Nov 21 - Ene 22,Dic 21 - Feb 22
0,% población en edad de trabajar,29.333815,29.211710,28.442504,28.844564,28.385436,27.979182,27.703478,27.689255,28.032216,27.422731,27.113461,27.545360
1,TGP,66.527311,65.181578,62.238623,61.432834,60.484874,60.982670,60.661422,59.305671,59.712203,57.110182,58.281598,58.937347
2,TO,47.139757,47.210011,45.300994,44.923838,43.729245,45.082902,46.419535,46.094901,46.935995,45.114417,45.041860,45.535015
3,TD,29.142249,27.571542,27.214017,26.873245,27.702181,26.072600,23.477637,22.275696,21.396279,21.004599,22.716808,22.739932
4,% Fuera de la fuerza laboral / PET 15 a 28 años,33.472689,34.818422,37.761377,38.567148,39.515108,39.017311,39.338597,40.694348,40.287815,42.889818,41.718402,41.062653
5,Población en edad de trabajar,6319.566667,6327.356333,6334.908667,6342.544667,6349.907667,6357.148000,6364.181667,6371.031000,6377.707333,6384.164667,6390.563667,6396.854667
6,Población en edad de trabajar 15 a 28 años,1853.770000,1848.329000,1801.806667,1829.479333,1802.449000,1778.678000,1763.099667,1764.091000,1787.812667,1750.712333,1732.703000,1762.036667
7,Fuerza de trabajo,1233.263333,1204.770000,1121.419667,1123.901000,1090.209000,1084.685333,1069.521333,1046.206000,1067.542333,999.835000,1009.847000,1038.497667
8,Ocupados,873.862667,872.596333,816.236333,821.872333,788.197333,801.879667,818.422667,813.156000,839.127667,789.823667,780.441667,802.343667
9,Desocupados,359.400667,332.173667,305.183333,302.028667,302.011667,282.805667,251.098333,233.049667,228.414333,210.011333,229.405000,236.153667
10,Fuera de la fuerza laboral,620.506667,643.559000,680.387000,705.578000,712.239667,693.992333,693.578667,717.885333,720.270667,750.877333,722.856000,723.539000

In [10]:
#datos 2022
names_col_22= ["Poblaciones", "Ene - Mar","Feb - Abr", "Mar - May", "Abr - Jun", "May - Jul"]

t18_22_j = pd.read_excel("G:/Unidades compartidas/Mercado laboral/Datos/1_Raw/anexo_GEIH_juventud_may22_jul22.xls",     
                       sheet_name = "23 áreas trim movil", header = 0,
                       skiprows = range(31), nrows = 11, usecols = "A, N:R", names =names_col_22)
t18_22_j

,Poblaciones,Ene - Mar,Feb - Abr,Mar - May,Abr - Jun,May - Jul
0,% población en edad de trabajar,27.780787,28.087690,27.799747,27.743858,27.055801
1,TGP,60.336724,58.641822,57.241070,56.417478,55.062379
2,TO,46.351159,47.001148,46.500481,46.326684,44.978395
3,TD,23.179161,19.850496,18.763813,17.885968,18.313747
4,% Fuera de la fuerza laboral / PET 15 a 28 años,39.663276,41.358160,42.758912,43.582504,44.937621
5,Población en edad de trabajar,6402.928667,6408.935667,6414.831667,6420.902333,6426.901333
6,Población en edad de trabajar 15 a 28 años,1778.784000,1800.122000,1783.307000,1781.406000,1738.849667
7,Fuerza de trabajo,1073.260000,1055.624333,1020.784000,1005.024333,957.452000
8,Ocupados,824.487000,846.078000,829.246333,825.266333,782.106667
9,Desocupados,248.772667,209.546667,191.538000,179.758333,175.345333
10,Fuera de la fuerza laboral,705.524000,744.497333,762.522667,776.381333,781.397667

#### Transponer

In [11]:
#establecer indice y transponer
frames_18 = [t18_21_j, t18_22_j]

for i in (frames_18):
    i.set_index("Poblaciones", inplace =True)

t18_21_j_t = t18_21_j.transpose()
t18_22_j_t = t18_22_j.transpose()

In [12]:
## homogenizar nombres de variables y asignar variable de año
frames_18_t = [t18_21_j_t, t18_22_j_t]

names_j = {'index':'Trimestre','% población en edad de trabajar ': "%PET_j", 
           '% Fuera de la fuerza laboral / PET 15 a 28 años': '%FFL_j/PET_j',
           'Población en edad de trabajar':'PET_T',
           'Población en edad de trabajar 15 a 28 años':'PET_j', 
           'Fuerza de trabajo':'FT_j', 'Ocupados': 'Ocupados_j',
           'Desocupados': 'Desocupados_j', 'Fuera de la fuerza laboral': 'FFL_j',
           'TGP':'TGP_j', 'TO': 'TO_j', 'TD':'TD_j'}
# names_nj = {'index':'Trimestre','% población en edad de trabajar ': "%PET_nj", 
#                               'Población en edad de trabajar':'PET_nj', 
#                                'Fuerza de trabajo':'FT_nj', 'Desocupados': 'Desocupados_nj',
#                               'Ocupados': 'Ocupados_nj', 'TGP':'TGP_nj', 'TO': 'TO_nj', 'TD':'TD_nj'}
names_col = [names_j, names_j]
per = [2021, 2022]

for i, j, k in zip(frames_18_t, names_col, per):
    i.reset_index(inplace =True)
    i.rename(columns = j, inplace =True)
    i = i.insert(0, "Periodo",  k)

In [13]:
#cargue totales 2019-2022 
names_col_21 = ["Periodo", "Trimestre", 'TGP', 'TO', 'TD',"PET_T", 
                "FT_T", "Ocupados_T", "Desocupados_T", "FFL_T"]
t18_Tot = pd.read_excel("G:/Unidades compartidas/Mercado laboral/Datos/4_Output/ml_pob_impu_19_22.xlsx",     
                       sheet_name = "bogotá trim movil", header = 0,
                         nrows = 41, usecols = "A,B, D:F, J:N", names = names_col_21 )
##datos 2021
msk_19_T = t18_Tot["Periodo"]==2019
t18_19_Tot = t18_Tot[msk_19_T==True]
t18_19_Tot.reset_index(inplace=True)

msk_T = t18_Tot["Periodo"]==2021
t18_21_Tot = t18_Tot[msk_T==True]
t18_21_Tot.reset_index(inplace=True)
##datos 2022
msk_T_2 = t18_Tot["Periodo"]==2022
t18_22_Tot = t18_Tot[msk_T_2 ==True]
t18_22_Tot.reset_index(inplace=True)

In [14]:
t18_21_Tot.columns

Index(['index', 'Periodo', 'Trimestre', 'TGP', 'TO', 'TD', 'PET_T', 'FT_T',
       'Ocupados_T', 'Desocupados_T', 'FFL_T'],
      dtype='object')

In [15]:
### crear variables para los no jovenes 2021-2022 marco 2018 dividios en mil
# ['PET', 'FT', 'Ocupados', 'Desocupados'] 2021 - ['PET_j', 'FT_j', 'Ocupados_j', 'Desocupados_j'] 2021
new_nj = ['PET_nj', 'FT_nj', 'Ocupados_nj', 'Desocupados_nj']
var_T = ["PET_T", "FT_T", "Ocupados_T", "Desocupados_T"]
var_j = ['PET_j', 'FT_j', 'Ocupados_j', 'Desocupados_j']
for i,j, k in zip(new_nj,var_T, var_j):
    t18_21_j_t[i] = ((t18_21_Tot[j]/1000) - t18_21_j_t[k])
    t18_22_j_t[i] = ((t18_22_Tot[j]/1000) - t18_22_j_t[k])

In [16]:
#variables poblacionales , 'TGP_nj',	'TO_nj','TD_nj'
l11 = ['TGP_nj','TO_nj','TD_nj']
l33_n = ['FT_nj', 'Ocupados_nj', 'Desocupados_nj']
l44_d = ['PET_nj', 'PET_nj', 'FT_nj']
for i, j, k in zip(l11, l33_n, l44_d):
    t18_21_j_t[i] = (t18_21_j_t[j] / t18_21_j_t[k]*100).astype(np.double)
    t18_22_j_t[i] = (t18_22_j_t[j] / t18_22_j_t[k]*100).astype(np.double)

#### Imputar 2019 y 2020

##### Variables poblacionales

In [17]:
#print(t18_21_j_t.columns, t05_19t.columns)

In [18]:
#variables poblacionales
l1 = ['PET_j', 'FT_j', 'Ocupados_j', 'Desocupados_j', 
      'PET_nj', 'FT_nj', 'Ocupados_nj', 'Desocupados_nj']
ld = ['PET_nj', 'FT_nj', 'Ocupados_nj', 'Desocupados_nj',
      'PET_j', 'FT_j', 'Ocupados_j', 'Desocupados_j']
lt = ["PET_T", "FT_T",  "Ocupados_T", "Desocupados_T",
      "PET_T", "FT_T",  "Ocupados_T", "Desocupados_T"]

In [19]:
### 2019_impu  = (2021 marco 2018 / 2021 marco 2005) * 2019 marco 2005
#impuar valores 2019. nan quedan nan
t05_19t_imp = t05_19t.copy()
t05_20t_imp = t05_20t.copy()

for i, j, k in zip(l1, ld, lt):
    t05_19t_imp[i] = ((t05_19t[i] / (t05_19t[i]+ t05_19t[j])) * (t18_19_Tot[k]/1000)).astype(np.double)
    t05_20t_imp [i] = ((t05_19t_imp[i] *
                              (1 + ((t05_20t[i] - t05_19t[i]) / t05_19t[i])))).astype(np.double)

##### Tasas

In [20]:
t05_19t_imp.columns

Index(['Periodo', 'Trimestre', 'PET_j', 'FT_j', 'Desocupados_j', 'Ocupados_j',
       'Informal_j', 'TO_j', 'TD_j', 'PET_nj', 'FT_nj', 'Desocupados_nj',
       'Ocupados_nj', 'Informal_nj', 'TO_nj', 'TD_nj'],
      dtype='object')

In [21]:
#variables tasas
l2 = ['TGP_j', 'TO_j', 'TD_j', 'TGP_nj', 'TO_nj', 'TD_nj']
l3_n = ['FT_j', 'Ocupados_j', 'Desocupados_j', 'FT_nj', 'Ocupados_nj', 'Desocupados_nj']
l4_d = ['PET_j', 'PET_j', 'FT_j', 'PET_nj', 'PET_nj', 'FT_nj']

In [22]:
#impuar valores 2019. nan quedan nan
for i, j, k in zip(l2, l3_n, l4_d):
    t05_19t_imp[i] = (t05_19t_imp[j] / t05_19t_imp[k]*100).astype(np.double)
    t05_20t_imp[i] = (t05_20t_imp[j] / t05_20t_imp[k]*100).astype(np.double)#.astype(int)

In [23]:
t05_19t_imp

,Periodo,Trimestre,PET_j,FT_j,Desocupados_j,Ocupados_j,Informal_j,TO_j,TD_j,PET_nj,FT_nj,Desocupados_nj,Ocupados_nj,Informal_nj,TO_nj,TD_nj,TGP_j,TGP_nj
0,2019,ene-mar,1906.858749,1280.155889,279.762740,1000.896037,307095.522602,52.489259,21.853803,4147.006918,3042.295098,290.758057,2745.032012,1.183310e+06,66.193090,9.557194,67.134280,73.361226
1,2019,feb-abr,1886.080831,1237.112274,245.406715,991.777165,334128.259464,52.584022,19.837061,4181.992836,3112.461126,264.165881,2846.503314,1.251588e+06,68.065715,8.487363,65.591689,74.425310
2,2019,mar-may,1873.742946,1211.678739,224.405770,987.213203,328825.067613,52.686693,18.520237,4208.298720,3122.755969,239.892031,2884.602727,1.315927e+06,68.545579,7.682061,64.666220,74.204713
3,2019,abr-jun,1852.805558,1210.497164,222.099792,988.393929,341323.923708,53.345799,18.347816,4243.485775,3170.316357,217.088777,2953.369004,1.314769e+06,69.597712,6.847543,65.333200,74.710192
4,2019,may-jul,1860.594501,1227.630082,222.095140,1005.638318,324509.039302,54.049301,18.091373,4249.495833,3115.382059,219.316963,2894.146903,1.316920e+06,68.105653,7.039810,65.980528,73.311804
5,2019,jun-ago,1817.006547,1168.843637,208.265613,960.998853,286754.111979,52.889124,17.818090,4306.652453,3161.363834,236.409662,2920.270241,1.279772e+06,67.808356,7.478091,64.327982,73.406523
6,2019,jul-sep,1873.058415,1184.127173,183.295510,1000.656462,288222.692213,53.423665,15.479377,4263.743585,3091.235812,237.782812,2855.358253,1.272215e+06,66.968339,7.692160,63.218913,72.500509
7,2019,ago-oct,1881.304718,1171.078389,192.595089,980.599817,282461.438035,52.123391,16.445960,4268.242616,3072.675308,246.228166,2816.333036,1.271714e+06,65.983434,8.013478,62.248203,71.989237
8,2019,sep-nov,1904.701311,1221.535266,207.987394,1017.903370,324035.712900,53.441627,17.026720,4257.216689,3101.529197,230.452041,2855.557101,1.329629e+06,67.075681,7.430272,64.132642,72.853449
9,2019,oct-dic,1836.077771,1210.209723,256.904442,971.566776,328803.242823,52.915339,21.228093,4337.751229,3169.397177,239.132789,2899.437229,1.348845e+06,66.841944,7.545056,65.912770,73.065444
10,2019,nov19-ene20,NaN,NaN,NaN,NaN,313370.340052,NaN,NaN,NaN,NaN,NaN,NaN,1.334281e+06,NaN,NaN,NaN,NaN
11,2019,dic19-feb20,NaN,NaN,NaN,NaN,304062.419465,NaN,NaN,NaN,NaN,NaN,NaN,1.339247e+06,NaN,NaN,NaN,NaN

In [24]:
#observar si los nombres de las columnas de ambos dataset son iguales
#(t05_19t_imp.columns, t05_20t_imp.columns)

#### Concatenar

In [25]:
#concat 2021-2022 hombres y mujeres.
f_frames = [t05_19t_imp, t05_20t_imp, t18_21_j_t, t18_22_j_t]
j_nj_impu_19_22 = pd.concat(f_frames)

In [26]:
##eliminar variables que no tienen marco muestral 2005
j_nj_impu_19_22.drop(columns=["%PET_j",	"%FFL_j/PET_j",	"PET_T", "FFL_j"], inplace = True)

In [27]:
#poblaciones a millones enteros de l1
for i in (l1):
    j_nj_impu_19_22[i] = j_nj_impu_19_22[i]*1000

In [28]:
### marca valores imputados
def m_imp(df):
    if ((df["Periodo"] == 2019 or df["Periodo"] == 2020) 
        and (pd.notnull(df["PET_j"]))): 
        x = 1
    elif ((df["Periodo"] == 2019 or df["Periodo"] == 2020) 
        and (pd.isnull(df["PET_j"]))):
        x = np.nan
    else:
        x = 0
    return(x)

In [29]:
j_nj_impu_19_22["valor Imputado"] = j_nj_impu_19_22.apply(m_imp, axis=1)

In [30]:
#j_nj_impu_19_22.info()

In [31]:
##guardar en un solo archivo excel con distintas pestañas
ml_pob_impu_19_22 = pd.read_excel("G:/Unidades compartidas/Mercado laboral/Datos/4_Output/ml_pob_impu_19_22.xlsx",     
                       sheet_name = "bogotá trim movil", header = 0)

ml_pob_impu_19_22_sec = pd.read_excel("G:/Unidades compartidas/Mercado laboral/Datos/4_Output/ml_pob_impu_19_22.xlsx",     
                       sheet_name = "sectores", header = 0)

desag_impu_19_22 = pd.read_excel("G:/Unidades compartidas/Mercado laboral/Datos/4_Output/ml_pob_impu_19_22.xlsx",     
                       sheet_name = "sexo", header = 0)

writer = pd.ExcelWriter("G:/Unidades compartidas/Mercado laboral/Datos/4_Output/ml_pob_impu_19_22.xlsx")

ml_pob_impu_19_22.to_excel(writer, sheet_name = "bogotá trim movil", header = True, index=False)
ml_pob_impu_19_22_sec.to_excel(writer, sheet_name = "sectores", header = True, index=False)
desag_impu_19_22.to_excel(writer, sheet_name = "sexo", header = True, index=False)
j_nj_impu_19_22.to_excel(writer, sheet_name = "jov_nojov", header = True, index=False)

writer.save()
writer.close()