In [5]:
import pandas as pd
import numpy as np
from numpy import average
from pandas_profiling import ProfileReport
import dtale

In [2]:
import matplotlib.pyplot as plt
#import seaborn as sns
import plotly.graph_objects as go
from plotly.subplots import make_subplots 
import plotly.express as px

# Cargue de bases de datos

In [42]:
#cargue de base
segunda_vuelta = pd.read_excel("D:/one_drive_unal/OneDrive - Universidad Nacional de Colombia/análisis_electoral_2022/segunda_vuelta_presidencia/segunda_vuelta.xlsx",  
                           sheet_name="Sheet1", header=0)

In [7]:
censo_electoral = pd.read_excel("D:/one_drive_unal/OneDrive - Universidad Nacional de Colombia/análisis_electoral_2022/Divipole_Elecciones_Congreso_13_03_2022.xlsx",
                           sheet_name="divipol", header=0)

In [65]:
censo_electoral.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12512 entries, 0 to 12511
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   dd            12512 non-null  object
 1   mm            12512 non-null  float64
 2   zz            12512 non-null  float64
 3   pp            12512 non-null  object
 4   departamento  12512 non-null  object
 5   municipio     12512 non-null  object
 6   puesto        12512 non-null  object
 7   mujeres       12512 non-null  int64
 8   hombres       12512 non-null  int64
 9   total         12512 non-null  int64
 10  mesas         12512 non-null  int64
 11  comuna        3803 non-null   object
dtypes: float64(2), int64(4), object(6)
memory usage: 1.1+ MB

In [69]:
#print(list(censo_electoral["municipio"].tail(100)))
#print(list(primera_vuelta["Municipio"].tail(100)))
censo_electoral = censo_electoral.iloc[:12512,:]
censo_electoral.tail()

,dd,mm,zz,pp,departamento,municipio,puesto,mujeres,hombres,total,mesas,comuna
12507,88,815.0,65.0,06,CONSULADOS,VENEZUELA,San Cristóbal -García de Hevia,516,520,1036,1,NaN
12508,88,815.0,65.0,07,CONSULADOS,VENEZUELA,San Cristóbal - Jauregui,70,153,223,1,NaN
12509,88,815.0,65.0,08,CONSULADOS,VENEZUELA,San Cristóbal - Torbes,171,153,324,1,NaN
12510,88,815.0,70.0,02,CONSULADOS,VENEZUELA,San Fernando de Atabapo - Consulado,271,303,574,1,NaN
12511,88,815.0,75.0,02,CONSULADOS,VENEZUELA,Valencia - Consulado,10437,9673,20110,9,NaN

In [110]:
segunda_vuelta.tail()

,Codigo_Depto,Nombre_Depto,Code_Mpio,Mombre_Municipio,zona,puesto,Nombre_ Puesto,Mesa,COALICIÓN PACTO HISTÓRICO,LIGA DE GOBERNANTES ANTICORRUPCIÓN,Tarjetones No Marcados,Votos en blanco,Votos nulos,Total Votos por Mesa,Censo Hombres Por Puesto,Censo Mujeres Por puesto,Censo Total Por puesto
103310,9.0,CALDAS,85.0,PENSILVANIA,99.0,5,BOLIVIA,1.0,35.0,213.0,1.0,3.0,4.0,256.0,854.0,1015.0,1869.0
103311,9.0,CALDAS,85.0,PENSILVANIA,99.0,5,BOLIVIA,2.0,30.0,200.0,1.0,3.0,4.0,238.0,854.0,1015.0,1869.0
103312,9.0,CALDAS,85.0,PENSILVANIA,99.0,5,BOLIVIA,3.0,22.0,173.0,2.0,10.0,7.0,214.0,854.0,1015.0,1869.0
103313,9.0,CALDAS,85.0,PENSILVANIA,99.0,5,BOLIVIA,4.0,160.0,52.0,1.0,1.0,3.0,217.0,854.0,1015.0,1869.0
103314,9.0,CALDAS,85.0,PENSILVANIA,99.0,5,BOLIVIA,5.0,44.0,115.0,0.0,6.0,8.0,173.0,854.0,1015.0,1869.0

In [32]:
segunda_vuelta[segunda_vuelta["Nombre_Depto"]=="SANTANDER"][segunda_vuelta["Mombre_Municipio"]=="BUCARAMANGA"][segunda_vuelta["Nombre_ Puesto"]=="AUDITORIO SENA"][segunda_vuelta["Mesa"]==4]

<ipython-input-32-470d802dfed0>:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

,Codigo_Depto,Nombre_Depto,Code_Mpio,Mombre_Municipio,zona,puesto,Nombre_ Puesto,Mesa,COALICIÓN PACTO HISTÓRICO,LIGA DE GOBERNANTES ANTICORRUPCIÓN,Tarjetones No Marcados,Votos en blanco,Votos nulos,Total Votos por Mesa,Censo Hombres Por Puesto,Censo Mujeres Por puesto,Censo Total Por puesto
59860,27.0,SANTANDER,1.0,BUCARAMANGA,3.0,4,AUDITORIO SENA,4.0,28.0,142.0,0.0,2.0,1.0,173.0,3115.0,1300.0,4415.0

# Modulo de Consultas

In [24]:
segunda_vuelta[segunda_vuelta["Mombre_Municipio"]=="IBAGUE"][segunda_vuelta["Nombre_ Puesto"]=="IE GERMAN PARDO SEDE PRINCIPAL"][segunda_vuelta["Mesa"]==21]

<ipython-input-24-3e69364887ec>:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

,Codigo_Depto,Nombre_Depto,Code_Mpio,Mombre_Municipio,zona,puesto,Nombre_ Puesto,Mesa,COALICIÓN PACTO HISTÓRICO,LIGA DE GOBERNANTES ANTICORRUPCIÓN,Tarjetones No Marcados,Votos en blanco,Votos nulos,Total Votos por Mesa,Censo Hombres Por Puesto,Censo Mujeres Por puesto,Censo Total Por puesto
66223,29.0,TOLIMA,1.0,IBAGUE,2.0,2,IE GERMAN PARDO SEDE PRINCIPAL,21.0,115.0,53.0,0.0,7.0,2.0,177.0,8054.0,1731.0,9785.0

In [25]:
#cantidad de mesas por puesto. Primera vuelta. 
segunda_vuelta[segunda_vuelta["Mombre_Municipio"]=="BOGOTA. D.C."][segunda_vuelta["Nombre_ Puesto"]=="LAS FERIAS"]["Mesa"].count()

<ipython-input-25-5402e0d28b29>:2: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

23

In [108]:
segunda_vuelta_1[segunda_vuelta_1["Mombre_Municipio"]=="BOGOTA. D.C."][segunda_vuelta_1["Nombre_ Puesto"]=="LAS FERIAS"]

<ipython-input-108-f466288f0bb0>:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

,Codigo_Depto,Nombre_Depto,Code_Mpio,Mombre_Municipio,zona,puesto,Nombre_ Puesto,Mesa,COALICIÓN PACTO HISTÓRICO,LIGA DE GOBERNANTES ANTICORRUPCIÓN,Tarjetones No Marcados,Votos en blanco,Votos nulos,Total Votos por Mesa,Censo Hombres Por Puesto,Censo Mujeres Por puesto,Censo Total Por puesto
5308,16.0,BOGOTA D.C.,1.0,BOGOTA. D.C.,10.0,20,LAS FERIAS,23,2831.0,2304.0,2.0,163.0,55.0,5355.0,4412.0,4276.0,8688.0

In [77]:
segunda_vuelta_1[segunda_vuelta_1["Mombre_Municipio"]=="BOGOTA. D.C."]["COALICIÓN PACTO HISTÓRICO"].sum()

2253997.0

In [107]:
segunda_vuelta_1[segunda_vuelta_1["Mombre_Municipio"]=="BOGOTA. D.C."]["Censo Total Por puesto"].sum()

5935722.0

In [56]:
segunda_vuelta_1["Censo Total Por puesto"].sum()

39771902.0

In [52]:
segunda_vuelta_1.tail()

,Codigo_Depto,Nombre_Depto,Code_Mpio,Mombre_Municipio,zona,puesto,Nombre_ Puesto,Mesa,COALICIÓN PACTO HISTÓRICO,LIGA DE GOBERNANTES ANTICORRUPCIÓN,Tarjetones No Marcados,Votos en blanco,Votos nulos,Total Votos por Mesa,Censo Hombres Por Puesto,Censo Mujeres Por puesto,Censo Total Por puesto
13209,88.0,CONSULADOS,815.0,VENEZUELA,75.0,82,MARTES VALENCIA - CONSULADO,1,0.0,3.0,0.0,0.0,0.0,3.0,300.0,394.0,694.0
13210,88.0,CONSULADOS,815.0,VENEZUELA,75.0,83,MIERCOLES VALENCIA - CONSULADO,1,0.0,7.0,0.0,0.0,0.0,7.0,300.0,394.0,694.0
13211,88.0,CONSULADOS,815.0,VENEZUELA,75.0,84,JUEVES VALENCIA - CONSULADO,1,0.0,12.0,0.0,0.0,0.0,12.0,300.0,394.0,694.0
13212,88.0,CONSULADOS,815.0,VENEZUELA,75.0,85,VIERNES VALENCIA - CONSULADO,1,1.0,5.0,0.0,0.0,0.0,6.0,300.0,394.0,694.0
13213,88.0,CONSULADOS,815.0,VENEZUELA,75.0,86,SABADO VALENCIA - CONSULADO,1,5.0,3.0,0.0,0.0,1.0,9.0,300.0,394.0,694.0

In [57]:
##NÚMERO DE MESAS TOTALES
#censo_electoral.iloc[12512,:]

In [47]:
#NÚMERO DE MESAS EN VOTACIÓN PRIMERA VUELTA
segunda_vuelta["Mesa"].count()

103315

# Transformación base d resultados para pegue

In [78]:
segunda_vuelta_1= segunda_vuelta.groupby(
    ["Codigo_Depto","Nombre_Depto", "Code_Mpio", "Mombre_Municipio", "zona", "puesto", "Nombre_ Puesto"]).agg(
    {"Mesa": np.size, "COALICIÓN PACTO HISTÓRICO":np.sum,
      "LIGA DE GOBERNANTES ANTICORRUPCIÓN":np.sum,	"Tarjetones No Marcados":np.sum, "Votos en blanco":np.sum,
      "Votos nulos":np.sum, "Total Votos por Mesa":np.sum,"Censo Hombres Por Puesto":np.min, 
     "Censo Mujeres Por puesto":np.min, "Censo Total Por puesto":np.min}).reset_index()
#primera_vuelta.groupby(["COD_DANE","Departamento", "Municipio", "Puesto"]).sum().reset_index().tail()

In [73]:
segunda_vuelta_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13214 entries, 0 to 13213
Data columns (total 14 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Codigo_Depto                        13214 non-null  float64
 1   Nombre_Depto                        13214 non-null  object
 2   Code_Mpio                           13214 non-null  float64
 3   Mombre_Municipio                    13214 non-null  object
 4   zona                                13214 non-null  float64
 5   puesto                              13214 non-null  object
 6   Nombre_ Puesto                      13214 non-null  object
 7   Mesa                                13214 non-null  int64
 8   COALICIÓN PACTO HISTÓRICO           13214 non-null  float64
 9   LIGA DE GOBERNANTES ANTICORRUPCIÓN  13214 non-null  float64
 10  Tarjetones No Marcados              13214 non-null  float64
 11  Votos en blanco                     13214 non-null  float64
 12  Votos nulos                         13214 non-null  float64
 13  Total Votos por Mesa                13214 non-null  float64
dtypes: float64(9), int64(1), object(4)
memory usage: 1.4+ MB

In [68]:
segunda_vuelta_1.head(5)

,Codigo_Depto,Nombre_Depto,Code_Mpio,Mombre_Municipio,zona,puesto,Nombre_ Puesto,Mesa,COALICIÓN PACTO HISTÓRICO,LIGA DE GOBERNANTES ANTICORRUPCIÓN,Tarjetones No Marcados,Votos en blanco,Votos nulos,Total Votos por Mesa,Censo Hombres Por Puesto,Censo Mujeres Por puesto,Censo Total Por puesto
0,1.0,ANTIOQUIA,1.0,MEDELLIN,1.0,1,SEC. ESC. LA ESPERANZA NO 2,32,1815.0,2065.0,6.0,236.0,104.0,4226.0,4975.0,7439.0,12414.0
1,1.0,ANTIOQUIA,1.0,MEDELLIN,1.0,2,INST.EDUC. LA CANDELARIA,45,3031.0,3813.0,19.0,305.0,215.0,7383.0,10595.0,6750.0,17345.0
2,1.0,ANTIOQUIA,1.0,MEDELLIN,1.0,3,IE.MARIA DE LOS ANGELES CANO MARQUEZ,20,1877.0,1904.0,6.0,152.0,161.0,4100.0,4140.0,3392.0,7532.0
3,1.0,ANTIOQUIA,1.0,MEDELLIN,1.0,4,SEC. ESC. MEDELLIN,22,1642.0,2446.0,14.0,175.0,140.0,4417.0,4655.0,3716.0,8371.0
4,1.0,ANTIOQUIA,1.0,MEDELLIN,1.0,5,I.E.FE Y ALEGRIA GRANIZAL,8,829.0,490.0,3.0,43.0,35.0,1400.0,1567.0,1400.0,2967.0

In [114]:
segunda_vuelta_1["Nombre_ Puesto"] = segunda_vuelta_1["Nombre_ Puesto"].str.upper()
censo_electoral["puesto"] = censo_electoral["puesto"].str.upper()

In [120]:
sgda_vuelta_censo = pd.merge(left=segunda_vuelta_1, right=censo_electoral, 
                            left_on=["Nombre_Depto", "Mombre_Municipio", "zona","Nombre_ Puesto"], #"Zona", "zz",
                            right_on=["departamento", "municipio",  "zz", "puesto"], how = 'outer', sort =False,
                            validate = 'm:m', suffixes=("_resultado", "_censo"),
                            indicator = 'indicator_column')

In [121]:
sgda_vuelta_censo[sgda_vuelta_censo["Mombre_Municipio"]=="BOGOTA. D.C."]["COALICIÓN PACTO HISTÓRICO"].sum()

2253997.0

In [122]:
sgda_vuelta_censo["COALICIÓN PACTO HISTÓRICO"].sum()

11280772.0

In [85]:
sgda_vuelta_censo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13535 entries, 0 to 13534
Data columns (total 30 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Codigo_Depto                        13216 non-null  float64
 1   Nombre_Depto                        13216 non-null  object
 2   Code_Mpio                           13216 non-null  float64
 3   Mombre_Municipio                    13216 non-null  object
 4   zona                                13216 non-null  float64
 5   puesto_resultado                    13216 non-null  object
 6   Nombre_ Puesto                      13216 non-null  object
 7   Mesa                                13216 non-null  float64
 8   COALICIÓN PACTO HISTÓRICO           13216 non-null  float64
 9   LIGA DE GOBERNANTES ANTICORRUPCIÓN  13216 non-null  float64
 10  Tarjetones No Marcados              13216 non-null  float64
 11  Votos en blanco                     13216 non-null  float64
 12  Votos nulos                         13216 non-null  float64
 13  Total Votos por Mesa                13216 non-null  float64
 14  Censo Hombres Por Puesto            13216 non-null  float64
 15  Censo Mujeres Por puesto            13216 non-null  float64
 16  Censo Total Por puesto              13216 non-null  float64
 17  dd                                  12514 non-null  object
 18  mm                                  12514 non-null  float64
 19  zz                                  12514 non-null  float64
 20  pp                                  12514 non-null  object
 21  departamento                        12514 non-null  object
 22  municipio                           12514 non-null  object
 23  puesto_censo                        12514 non-null  object
 24  mujeres                             12514 non-null  float64
 25  hombres                             12514 non-null  float64
 26  total                               12514 non-null  float64
 27  mesas                               12514 non-null  float64
 28  comuna                              3803 non-null   object
 29  indicator_column                    13535 non-null  category
dtypes: category(1), float64(19), object(10)
memory usage: 3.1+ MB

In [87]:
sgda_vuelta_censo.head()

,Codigo_Depto,Nombre_Depto,Code_Mpio,Mombre_Municipio,zona,puesto_resultado,Nombre_ Puesto,Mesa,COALICIÓN PACTO HISTÓRICO,LIGA DE GOBERNANTES ANTICORRUPCIÓN,...,pp,departamento,municipio,puesto_censo,mujeres,hombres,total,mesas,comuna,indicator_column
0,1.0,ANTIOQUIA,1.0,MEDELLIN,1.0,1,SEC. ESC. LA ESPERANZA NO 2,32.0,1815.0,2065.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,1.0,ANTIOQUIA,1.0,MEDELLIN,1.0,2,INST.EDUC. LA CANDELARIA,45.0,3031.0,3813.0,...,02,ANTIOQUIA,MEDELLIN,INST.EDUC. LA CANDELARIA,11117.0,6890.0,18007.0,51.0,01COMUNA 1 POPULAR,both
2,1.0,ANTIOQUIA,1.0,MEDELLIN,1.0,3,IE.MARIA DE LOS ANGELES CANO MARQUEZ,20.0,1877.0,1904.0,...,03,ANTIOQUIA,MEDELLIN,IE.MARIA DE LOS ANGELES CANO MARQUEZ,4097.0,3360.0,7457.0,22.0,01COMUNA 1 POPULAR,both
3,1.0,ANTIOQUIA,1.0,MEDELLIN,1.0,4,SEC. ESC. MEDELLIN,22.0,1642.0,2446.0,...,04,ANTIOQUIA,MEDELLIN,SEC. ESC. MEDELLIN,4724.0,3756.0,8480.0,24.0,01COMUNA 1 POPULAR,both
4,1.0,ANTIOQUIA,1.0,MEDELLIN,1.0,5,I.E.FE Y ALEGRIA GRANIZAL,8.0,829.0,490.0,...,05,ANTIOQUIA,MEDELLIN,I.E.FE Y ALEGRIA GRANIZAL,1383.0,1223.0,2606.0,8.0,01COMUNA 1 POPULAR,both

In [123]:
sgda_vuelta_censo[sgda_vuelta_censo["Nombre_Depto"]=="SANTANDER"][sgda_vuelta_censo["Mombre_Municipio"]=="BUCARAMANGA"][sgda_vuelta_censo["Nombre_ Puesto"]=="AUDITORIO SENA"]

<ipython-input-123-7cf29259aca4>:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

,Codigo_Depto,Nombre_Depto,Code_Mpio,Mombre_Municipio,zona,puesto_resultado,Nombre_ Puesto,Mesa,COALICIÓN PACTO HISTÓRICO,LIGA DE GOBERNANTES ANTICORRUPCIÓN,Tarjetones No Marcados,Votos en blanco,Votos nulos,Total Votos por Mesa,Censo Hombres Por Puesto,Censo Mujeres Por puesto,Censo Total Por puesto,dd,mm,zz,pp,departamento,municipio,puesto_censo,mujeres,hombres,total,mesas,comuna,indicator_column
8451,27.0,SANTANDER,1.0,BUCARAMANGA,3.0,4,AUDITORIO SENA,12.0,996.0,1763.0,2.0,49.0,8.0,2818.0,3115.0,1300.0,4415.0,27,1.0,3.0,04,SANTANDER,BUCARAMANGA,AUDITORIO SENA,3114.0,1196.0,4310.0,13.0,03COMUNA 3 SAN FRANCISCO,both

### Validaión de pegue

In [124]:
l1 = ["COALICIÓN PACTO HISTÓRICO",  "LIGA DE GOBERNANTES ANTICORRUPCIÓN",  "Tarjetones No Marcados",
      "Votos en blanco", "Votos nulos","Total Votos por Mesa", "Censo Total Por puesto", "total"]
for i in l1:
    print(pd.to_numeric(sgda_vuelta_censo[i]).sum())

11280772.0
10579828.0
23615.0
501980.0
271667.0
22657862.0
39772128.0
38820129.0

In [126]:
segunda_vuelta.tail()

,Codigo_Depto,Nombre_Depto,Code_Mpio,Mombre_Municipio,zona,puesto,Nombre_ Puesto,Mesa,COALICIÓN PACTO HISTÓRICO,LIGA DE GOBERNANTES ANTICORRUPCIÓN,Tarjetones No Marcados,Votos en blanco,Votos nulos,Total Votos por Mesa,Censo Hombres Por Puesto,Censo Mujeres Por puesto,Censo Total Por puesto
103310,9.0,CALDAS,85.0,PENSILVANIA,99.0,5,BOLIVIA,1.0,35.0,213.0,1.0,3.0,4.0,256.0,854.0,1015.0,1869.0
103311,9.0,CALDAS,85.0,PENSILVANIA,99.0,5,BOLIVIA,2.0,30.0,200.0,1.0,3.0,4.0,238.0,854.0,1015.0,1869.0
103312,9.0,CALDAS,85.0,PENSILVANIA,99.0,5,BOLIVIA,3.0,22.0,173.0,2.0,10.0,7.0,214.0,854.0,1015.0,1869.0
103313,9.0,CALDAS,85.0,PENSILVANIA,99.0,5,BOLIVIA,4.0,160.0,52.0,1.0,1.0,3.0,217.0,854.0,1015.0,1869.0
103314,9.0,CALDAS,85.0,PENSILVANIA,99.0,5,BOLIVIA,5.0,44.0,115.0,0.0,6.0,8.0,173.0,854.0,1015.0,1869.0

In [127]:
l1 = ["COALICIÓN PACTO HISTÓRICO",  "LIGA DE GOBERNANTES ANTICORRUPCIÓN",  "Tarjetones No Marcados",
      "Votos en blanco", "Votos nulos","Total Votos por Mesa"]
for i in l1:
    print(pd.to_numeric(segunda_vuelta[i]).sum())

11280694.0
10579803.0
23615.0
501976.0
271665.0
22657753.0

In [128]:
#pra_vuelta_censo.head(50)
sgda_vuelta_censo[sgda_vuelta_censo["Mombre_Municipio"]=="BOGOTA. D.C."]["COALICIÓN PACTO HISTÓRICO"].sum()

2253997.0

In [129]:
sgda_vuelta_censo["Total Votos por Mesa"].sum() #total

22657862.0

# Base final para visor de datos

In [101]:
pd.options.display.max_columns = None #max_rows muestra el total de filas
sgda_vuelta_censo.head()

,Codigo_Depto,Nombre_Depto,Code_Mpio,Mombre_Municipio,zona,puesto_resultado,Nombre_ Puesto,Mesa,COALICIÓN PACTO HISTÓRICO,LIGA DE GOBERNANTES ANTICORRUPCIÓN,Tarjetones No Marcados,Votos en blanco,Votos nulos,Total Votos por Mesa,Censo Hombres Por Puesto,Censo Mujeres Por puesto,Censo Total Por puesto,dd,mm,zz,pp,departamento,municipio,puesto_censo,mujeres,hombres,total,mesas,comuna,indicator_column
0,1.0,ANTIOQUIA,1.0,MEDELLIN,1.0,1,SEC. ESC. LA ESPERANZA NO 2,32.0,1815.0,2065.0,6.0,236.0,104.0,4226.0,4975.0,7439.0,12414.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,1.0,ANTIOQUIA,1.0,MEDELLIN,1.0,2,INST.EDUC. LA CANDELARIA,45.0,3031.0,3813.0,19.0,305.0,215.0,7383.0,10595.0,6750.0,17345.0,01,1.0,1.0,02,ANTIOQUIA,MEDELLIN,INST.EDUC. LA CANDELARIA,11117.0,6890.0,18007.0,51.0,01COMUNA 1 POPULAR,both
2,1.0,ANTIOQUIA,1.0,MEDELLIN,1.0,3,IE.MARIA DE LOS ANGELES CANO MARQUEZ,20.0,1877.0,1904.0,6.0,152.0,161.0,4100.0,4140.0,3392.0,7532.0,01,1.0,1.0,03,ANTIOQUIA,MEDELLIN,IE.MARIA DE LOS ANGELES CANO MARQUEZ,4097.0,3360.0,7457.0,22.0,01COMUNA 1 POPULAR,both
3,1.0,ANTIOQUIA,1.0,MEDELLIN,1.0,4,SEC. ESC. MEDELLIN,22.0,1642.0,2446.0,14.0,175.0,140.0,4417.0,4655.0,3716.0,8371.0,01,1.0,1.0,04,ANTIOQUIA,MEDELLIN,SEC. ESC. MEDELLIN,4724.0,3756.0,8480.0,24.0,01COMUNA 1 POPULAR,both
4,1.0,ANTIOQUIA,1.0,MEDELLIN,1.0,5,I.E.FE Y ALEGRIA GRANIZAL,8.0,829.0,490.0,3.0,43.0,35.0,1400.0,1567.0,1400.0,2967.0,01,1.0,1.0,05,ANTIOQUIA,MEDELLIN,I.E.FE Y ALEGRIA GRANIZAL,1383.0,1223.0,2606.0,8.0,01COMUNA 1 POPULAR,both

In [138]:
sgda_vuelta_censo[sgda_vuelta_censo["Nombre_ Puesto"]=="COLEGIO CAMILO C RESTREPO"]

,Codigo_Depto,Nombre_Depto,Code_Mpio,Mombre_Municipio,zona,puesto_resultado,Nombre_ Puesto,Mesa,COALICIÓN PACTO HISTÓRICO,LIGA DE GOBERNANTES ANTICORRUPCIÓN,Tarjetones No Marcados,Votos en blanco,Votos nulos,Total Votos por Mesa,Censo Hombres Por Puesto,Censo Mujeres Por puesto,Censo Total Por puesto,dd,mm,zz,pp,departamento,municipio,puesto_censo,mujeres,hombres,total,mesas,comuna,indicator_column
175,1.0,ANTIOQUIA,1.0,MEDELLIN,29.0,1,COLEGIO CAMILO C RESTREPO,19.0,1218.0,3017.0,4.0,127.0,92.0,4458.0,4028.0,3233.0,7261.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [162]:
#print(list(segunda_vuelta["Mombre_Municipio"]))

In [170]:
mask = segunda_vuelta["Mombre_Municipio"]=="BOGOTA. D.C."
mask[segunda_vuelta["zona"]==16])

In [147]:
#sgda_vuelta_censo[sgda_vuelta_censo["puesto_censo"]=="COLEGIO CAMILO C RESTREPO"]
censo_electoral[censo_electoral["municipio"]=="MEDELLIN"][censo_electoral["zz"]==29]

<ipython-input-147-e52c32b834fd>:2: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

,dd,mm,zz,pp,departamento,municipio,puesto,mujeres,hombres,total,mesas,comuna
175,01,1.0,29.0,01,ANTIOQUIA,MEDELLIN,SEC.ESC.SANTISIMA TRINIDAD,4032,3210,7242,21,15COMUNA 15 GUAYABAL
176,01,1.0,29.0,02,ANTIOQUIA,MEDELLIN,I.E.BENJAMIN HERRERA,4048,3303,7351,21,15COMUNA 15 GUAYABAL
177,01,1.0,29.0,03,ANTIOQUIA,MEDELLIN,I.E.CRISTO REY,6770,5501,12271,35,15COMUNA 15 GUAYABAL
178,01,1.0,29.0,04,ANTIOQUIA,MEDELLIN,SECCION ESC REPUBLICA DE COSTA RICA,4796,3880,8676,25,15COMUNA 15 GUAYABAL
179,01,1.0,29.0,05,ANTIOQUIA,MEDELLIN,SEC.ESC.LA COLINA,3042,2537,5579,16,15COMUNA 15 GUAYABAL
180,01,1.0,29.0,06,ANTIOQUIA,MEDELLIN,I.E. LA SALLE CAMPO AMOR,2544,2138,4682,14,15COMUNA 15 GUAYABAL
181,01,1.0,29.0,07,ANTIOQUIA,MEDELLIN,SEC ESC CRISTO REY APOLO,763,691,1454,5,15COMUNA 15 GUAYABAL

In [151]:
mask = sgda_vuelta_censo["indicator_column"] == "right_only"
sgda_vuelta_censo[mask==True]

,Codigo_Depto,Nombre_Depto,Code_Mpio,Mombre_Municipio,zona,puesto_resultado,Nombre_ Puesto,Mesa,COALICIÓN PACTO HISTÓRICO,LIGA DE GOBERNANTES ANTICORRUPCIÓN,Tarjetones No Marcados,Votos en blanco,Votos nulos,Total Votos por Mesa,Censo Hombres Por Puesto,Censo Mujeres Por puesto,Censo Total Por puesto,dd,mm,zz,pp,departamento,municipio,puesto_censo,mujeres,hombres,total,mesas,comuna,indicator_column
13216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,1.0,29.0,01,ANTIOQUIA,MEDELLIN,SEC.ESC.SANTISIMA TRINIDAD,4032.0,3210.0,7242.0,21.0,15COMUNA 15 GUAYABAL,right_only
13217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,13.0,99.0,04,ANTIOQUIA,AMAGA,I.E. SAN FERNANDO DE AMAGA,40.0,54.0,94.0,1.0,NaN,right_only
13218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,55.0,0.0,01,ANTIOQUIA,BETULIA,COLISEO MARIO GIL,2655.0,2694.0,5349.0,16.0,NaN,right_only
13219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,121.0,5.0,05,ANTIOQUIA,ENVIGADO,ESC. JHON F KENNEDY,5271.0,6375.0,11646.0,33.0,NaN,right_only
13220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,166.0,2.0,01,ANTIOQUIA,LA ESTRELLA,UNIDAD DEPORTIVA INDERE,3518.0,3988.0,7506.0,22.0,NaN,right_only
13221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,214.0,3.0,01,ANTIOQUIA,RIONEGRO,OFICINAS ADMINISTRACION MUNICIPAL,4607.0,4006.0,8613.0,25.0,02COMUNA 2 SAN ANTONIO,right_only
13222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,218.0,99.0,01,ANTIOQUIA,SABANETA,I.E MARIA AUXILIADORA,120.0,97.0,217.0,1.0,NaN,right_only
13223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,250.0,2.0,02,ANTIOQUIA,SANTA ROSA DE OSOS,INSTITUTO NUESTRA SEÑORA DEL CARMEN,2585.0,2058.0,4643.0,14.0,NaN,right_only
13224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03,4.0,2.0,04,ATLANTICO,BARANOA,C.I.C DIVINO NIÑO,895.0,820.0,1715.0,5.0,NaN,right_only
13225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05,1.0,99.0,74,BOLIVAR,CARTAGENA,BAYUNCA 2 (SEDE LAS LATAS),145.0,169.0,314.0,1.0,02LOC. 2 LA VIRGEN Y TURISTICA,right_only
13226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05,37.0,99.0,25,BOLIVAR,MARGARITA,MAMONCITO,586.0,676.0,1262.0,4.0,NaN,right_only
13227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05,73.0,99.0,05,BOLIVAR,SAN FERNANDO,MENCHIQUEJO,354.0,396.0,750.0,3.0,NaN,right_only
13228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05,79.0,1.0,01,BOLIVAR,SAN JUAN NEPOMUCENO,INS.ED.NORM.SUP.MONTES DE MAR,2505.0,4351.0,6856.0,20.0,NaN,right_only
13229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05,124.0,99.0,01,BOLIVAR,VILLANUEVA,CIPACOA,639.0,747.0,1386.0,4.0,NaN,right_only
13230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07,73.0,99.0,03,BOYACA,CHITA,EL ARENAL,0.0,0.0,0.0,0.0,NaN,right_only
13231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,88.0,1.0,03,CUNDINAMARCA,FUNZA,IED SERREZUELITA,1332.0,1308.0,2640.0,8.0,NaN,right_only
13232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,1.0,7.0,52,BOGOTA D.C.,BOGOTA. D.C.,ALMACEN METRO AUTOPISTA SUR,1494.0,1326.0,2820.0,8.0,07LOCALIDAD 7 BOSA,right_only
13233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,1.0,8.0,21,BOGOTA D.C.,BOGOTA. D.C.,BANDERAS GIMNASIO MILITAR FAC,4026.0,3615.0,7641.0,22.0,08LOCALIDAD 8 KENNEDY,right_only
13234,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,1.0,16.0,40,BOGOTA D.C.,BOGOTA. D.C.,PLAZA CENTRAL,1180.0,973.0,2153.0,7.0,16LOCALIDAD 16 PUENTE ARANDA,right_only
13235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,4.0,99.0,71,HUILA,ACEVEDO,I.E. SAN ISIDOR SEDE EL CARMEN,149.0,151.0,300.0,1.0,NaN,right_only
13236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,64.0,99.0,77,HUILA,RIVERA,I.E EL GUADAUAL,84.0,78.0,162.0,1.0,NaN,right_only
13237,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28,1.0,4.0,03,SUCRE,SINCELEJO,I.E.LUIS CARLOS GALAN,1609.0,1448.0,3057.0,9.0,05COMUNA 5 CENTRAL,right_only
13238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28,300.0,2.0,01,SUCRE,TOLU,I.E. SAN ISIDRO,1182.0,3742.0,4924.0,14.0,NaN,right_only
13239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,16.0,99.0,11,TOLIMA,ARMERO (GUAYABAL),SAN JORGE,23.0,31.0,54.0,1.0,NaN,right_only
13240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,73.0,99.0,26,TOLIMA,LIBANO,VEREDA CAMPOALEGRE,48.0,43.0,91.0,1.0,NaN,right_only
13241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,73.0,99.0,27,TOLIMA,LIBANO,VEREDA EL TESORO,54.0,70.0,124.0,1.0,08CORREGIMIENTO SAN FERNANDO,right_only
13242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,73.0,99.0,28,TOLIMA,LIBANO,VEREDA PATIO BONITO,55.0,71.0,126.0,1.0,05CORREGIMIENTO EL CONVENIO,right_only
13243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,73.0,99.0,29,TOLIMA,LIBANO,VEREDA SAN JORGE,51.0,68.0,119.0,1.0,NaN,right_only
13244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,1.0,31.0,05,VALLE,CALI,ESCUELA CELANESE,1189.0,994.0,2183.0,7.0,20COMUNA 20,right_only
13245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,19.0,1.0,03,VALLE,BUENAVENTURA,TERMINAL DE TRANSPORTE,1019.0,6173.0,7192.0,21.0,01LOCALIDAD 1 ISLA CASCAJAL,right_only
13246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,19.0,2.0,03,VALLE,BUENAVENTURA,INSTITUTO TECNICO COMERCIAL PILOTO,414.0,345.0,759.0,3.0,01LOCALIDAD 1 ISLA CASCAJAL,right_only
13247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,19.0,6.0,08,VALLE,BUENAVENTURA,SEDE MARIA AUXILIADORA,825.0,517.0,1342.0,4.0,02LOCALIDAD 2 CONT. (EL PAILON),right_only
13248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,106.0,6.0,02,VALLE,TULUA,ESCUELA RUBEN CRUZ VELEZ,6995.0,5772.0,12767.0,37.0,07COMUNA 7,right_only
13249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40,15.0,99.0,01,ARAUCA,CRAVO NORTE,VEREDA EL COROZO,0.0,0.0,0.0,0.0,NaN,right_only
13250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88,135.0,5.0,02,CONSULADOS,ARZERBAIYAN,BAKU CONSULADO,14.0,16.0,30.0,1.0,NaN,right_only
13251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88,305.0,5.0,01,CONSULADOS,CHILE,SANTIAGO EMBAJADA,3266.0,2982.0,6248.0,10.0,NaN,right_only
13252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88,355.0,5.0,01,CONSULADOS,ESPAÑA,MADRID - EMBAJADA,17425.0,15816.0,33241.0,48.0,NaN,right_only
13253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88,360.0,60.0,06,CONSULADOS,ESTADOS UNIDOS,SALT LAKE CITY,353.0,297.0,650.0,1.0,NaN,right_only
13254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88,360.0,60.0,09,CONSULADOS,ESTADOS UNIDOS,SAN FRANCISCO-LAS VEGAS NEVADA,341.0,229.0,570.0,1.0,NaN,right_only
13255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88,360.0,60.0,10,CONSULADOS,ESTADOS UNIDOS,SAN FRANCISCO - ALASKA,53.0,36.0,89.0,1.0,NaN,right_only
13256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88,360.0,60.0,11,CONSULADOS,ESTADOS UNIDOS,HAWAII,21.0,14.0,35.0,1.0,NaN,right_only
13257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88,380.0,5.0,01,CONSULADOS,FRANCIA,PARIS - EMBAJADA,2611.0,1933.0,4544.0,7.0,NaN,right_only
13258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88,683.0,5.0,05,CONSULADOS,PUERTO RICO,MAYAGÜEZ,113.0,120.0,233.0,1.0,NaN,right_only

In [714]:
list_1= ["zona","Mesa", "COALICIÓN PACTO HISTÓRICO",
      "LIGA DE GOBERNANTES ANTICORRUPCIÓN",	"Tarjetones No Marcados", "Votos en blanco",
      "Votos nulos", "Total Votos por Mesa","Censo Hombres Por Puesto",
      "Censo Mujeres Por puesto", "Censo Total Por puesto",
         "zz", "mm", "mujeres","hombres", "total", "mesas"]
#pra_vuelta_censo["Francia Márquez"] = round(pd.to_numeric(pra_vuelta_censo["Francia Márquez"], downcast='signed'),0)
for i in list_1:
    sgda_vuelta_censo[i] = (pd.Series(sgda_vuelta_censo[i], 
                                  dtype = "string").str.split('.', expand = True).get(0))

In [443]:
print(pd.to_numeric(primera_vuelta["Rodolfo Hernández"]).sum()) #5953209

5953209

In [681]:
#encontrar el registro duplicado y borrarlo
x = pra_vuelta_censo.groupby(["Departamento", "Municipio", "Zona","Puesto"]).aggregate({"Puesto": [np.size]})
mask_2 = x.iloc[:,0]>1
dupli = x[mask_2==True]
dupli

                                               Puesto
                                                 size
Departamento Municipio Zona Puesto
NARIÑO       TUMACO    99   GUACHAL LAS BRISAS      2

In [685]:
pd.options.display.max_columns = None #max_rows muestra el total de filas

In [720]:
pra_vuelta_censo[pra_vuelta_censo["Puesto"]=="GUACHAL LAS BRISAS"]

,COD_DANE,Departamento,Municipio,Zona,Puesto,# Mesa,Sergio Fajardo,Federico Gutiérrez,Gustavo Petro,John Milton Rodríguez,Luis Pérez,Rodolfo Hernández,Enrique Gómez,Ingrid Betancourt,Tarjetones No Marcados,Votos en blanco,Votos nulos,dd,mm,zz,pp,departamento,municipio,puesto,mujeres,hombres,total,mesas,comuna,indicator_column
8120,52835,NARIÑO,TUMACO,99,GUACHAL LAS BRISAS,2,9,37,58,1,0,2,0,1,0,5,0,23,139,99,44,NARIÑO,TUMACO,GUACHAL LAS BRISAS,57,68,125,1,NaN,both

In [719]:
#borrar el registro duplicado
pra_vuelta_censo = pra_vuelta_censo.drop(index = 8121)

KeyError: '[8121] not found in axis'

In [721]:
pra_vuelta_censo.to_csv("D:/one_drive_unal/OneDrive - Universidad Nacional de Colombia/análisis_electoral_2022/primera_vuelta_presidencia/result_primera_vuelta.csv", sep = ";", index=False)

### Comparar bases de datos

In [640]:
pra_vuelta_censo_1=pra_vuelta_censo.copy()
pra_vuelta_censo_1 = pra_vuelta_censo_1.iloc[:,:17]

In [653]:
primera_vuelta_2 = primera_vuelta_1.copy()
#primera_vuelta_2.loc[12504] = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

In [665]:
primera_vuelta_2.tail()

                                                                COD_DANE  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                  --
                            SAN CRISTÓBAL - TORBES                    --
                            SAN CRISTÓBAL -GARCÍA DE HEVIA            --
                       70   SAN FERNANDO DE ATABAPO - CONSULADO       --
                       75   VALENCIA - CONSULADO                      --

                                                                 # Mesa  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                  1
                            SAN CRISTÓBAL - TORBES                    1
                            SAN CRISTÓBAL -GARCÍA DE HEVIA            1
                       70   SAN FERNANDO DE ATABAPO - CONSULADO       1
                       75   VALENCIA - CONSULADO                      8

                                                                 Sergio Fajardo  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                          1
                            SAN CRISTÓBAL - TORBES                            0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                    0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO               0
                       75   VALENCIA - CONSULADO                              4

                                                                 Federico Gutiérrez  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                              0
                            SAN CRISTÓBAL - TORBES                                0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                        1
                       70   SAN FERNANDO DE ATABAPO - CONSULADO                   2
                       75   VALENCIA - CONSULADO                                 29

                                                                 Gustavo Petro  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                         1
                            SAN CRISTÓBAL - TORBES                           1
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                   5
                       70   SAN FERNANDO DE ATABAPO - CONSULADO              4
                       75   VALENCIA - CONSULADO                            14

                                                                 John Milton Rodríguez  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                                 0
                            SAN CRISTÓBAL - TORBES                                   0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                           0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO                      1
                       75   VALENCIA - CONSULADO                                     0

                                                                 Luis Pérez  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                      0
                            SAN CRISTÓBAL - TORBES                        0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO           0
                       75   VALENCIA - CONSULADO                          0

                                                                 Rodolfo Hernández  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                             2
                            SAN CRISTÓBAL - TORBES                               5
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                       6
                       70   SAN FERNANDO DE ATABAPO - CONSULADO                  2
                       75   VALENCIA - CONSULADO                                28

                                                                 Enrique Gómez  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                         0
                            SAN CRISTÓBAL - TORBES                           0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                   0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO              0
                       75   VALENCIA - CONSULADO                             0

                                                                 Ingrid Betancourt  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                             0
                            SAN CRISTÓBAL - TORBES                               0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                       0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO                  0
                       75   VALENCIA - CONSULADO                                 0

                                                                 Tarjetones No Marcados  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                                  0
                            SAN CRISTÓBAL - TORBES                                    0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                            0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO                       0
                       75   VALENCIA - CONSULADO                                      0

                                                                 Votos en blanco  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                           0
                            SAN CRISTÓBAL - TORBES                             2
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                     0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO                1
                       75   VALENCIA - CONSULADO                               1

                                                                 Votos nulos
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                       0
                            SAN CRISTÓBAL - TORBES                         0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                 0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO            0
                       75   VALENCIA - CONSULADO                           0

In [654]:
#indexar primera_vuelta_2
#list_1 = ["Departamento", "Municipio", "Zona","Puesto"]
primera_vuelta_2= primera_vuelta_2.set_index(["Departamento", "Municipio", "Zona","Puesto"], drop = True)

In [664]:
#indexar pra_vuelta_censo_1
#pra_vuelta_censo_1= pra_vuelta_censo_1.set_index(["Departamento", "Municipio", "Zona","Puesto"], drop = True)
pra_vuelta_censo_1.tail()

                                                                COD_DANE  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                  --
                            SAN CRISTÓBAL - TORBES                    --
                            SAN CRISTÓBAL -GARCÍA DE HEVIA            --
                       70   SAN FERNANDO DE ATABAPO - CONSULADO       --
                       75   VALENCIA - CONSULADO                      --

                                                                 # Mesa  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                  1
                            SAN CRISTÓBAL - TORBES                    1
                            SAN CRISTÓBAL -GARCÍA DE HEVIA            1
                       70   SAN FERNANDO DE ATABAPO - CONSULADO       1
                       75   VALENCIA - CONSULADO                      8

                                                                 Sergio Fajardo  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                          1
                            SAN CRISTÓBAL - TORBES                            0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                    0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO               0
                       75   VALENCIA - CONSULADO                              4

                                                                 Federico Gutiérrez  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                              0
                            SAN CRISTÓBAL - TORBES                                0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                        1
                       70   SAN FERNANDO DE ATABAPO - CONSULADO                   2
                       75   VALENCIA - CONSULADO                                 29

                                                                 Gustavo Petro  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                         1
                            SAN CRISTÓBAL - TORBES                           1
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                   5
                       70   SAN FERNANDO DE ATABAPO - CONSULADO              4
                       75   VALENCIA - CONSULADO                            14

                                                                 John Milton Rodríguez  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                                 0
                            SAN CRISTÓBAL - TORBES                                   0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                           0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO                      1
                       75   VALENCIA - CONSULADO                                     0

                                                                 Luis Pérez  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                      0
                            SAN CRISTÓBAL - TORBES                        0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO           0
                       75   VALENCIA - CONSULADO                          0

                                                                 Rodolfo Hernández  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                             2
                            SAN CRISTÓBAL - TORBES                               5
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                       6
                       70   SAN FERNANDO DE ATABAPO - CONSULADO                  2
                       75   VALENCIA - CONSULADO                                28

                                                                 Enrique Gómez  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                         0
                            SAN CRISTÓBAL - TORBES                           0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                   0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO              0
                       75   VALENCIA - CONSULADO                             0

                                                                 Ingrid Betancourt  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                             0
                            SAN CRISTÓBAL - TORBES                               0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                       0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO                  0
                       75   VALENCIA - CONSULADO                                 0

                                                                 Tarjetones No Marcados  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                                  0
                            SAN CRISTÓBAL - TORBES                                    0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                            0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO                       0
                       75   VALENCIA - CONSULADO                                      0

                                                                 Votos en blanco  \
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                           0
                            SAN CRISTÓBAL - TORBES                             2
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                     0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO                1
                       75   VALENCIA - CONSULADO                               1

                                                                 Votos nulos
Departamento Municipio Zona Puesto
CONSULADOS   VENEZUELA 65   SAN CRISTÓBAL - JAUREGUI                       0
                            SAN CRISTÓBAL - TORBES                         0
                            SAN CRISTÓBAL -GARCÍA DE HEVIA                 0
                       70   SAN FERNANDO DE ATABAPO - CONSULADO            0
                       75   VALENCIA - CONSULADO                           0

In [687]:
#dif =pra_vuelta_censo_1.compare(primera_vuelta_2, keep_shape=True, keep_equal= False)

In [ ]:
#dif.columns dif.info()

In [580]:
#dif[[('COD_DANE',  'self'), ('COD_DANE',  'other')]]
mask = dif[('COD_DANE',  'self')].notnull()
dif_2= dif[mask==True]

#dif[('COD_DANE',  'self')].value_counts()==1
# dif_2 = dif["COD_DANE"]!= 'NaN'
# dif_2.value_counts()
# dif_3 = dif_2[dif_2==True]
# dif_3

In [613]:
dif_2.iloc[:,:20].tail()

      COD_DANE        Departamento                   Municipio                 \
          self  other         self       other            self          other
12211    99001  99524          NaN         NaN  PUERTO CARREÑO   LA PRIMAVERA
12219    99524  99624          NaN         NaN    LA PRIMAVERA  SANTA ROSALIA
12223    99624  99773          NaN         NaN   SANTA ROSALIA       CUMARIBO
12255    99773     --      VICHADA  CONSULADOS        CUMARIBO       ALEMANIA
12504       --      0   CONSULADOS           0       VENEZUELA              0

       Zona                      Puesto                            # Mesa  \
       self other                  self                      other   self
12211  99.0   0.0        PUERTO MURILLO  PUESTO CABECERA MUNICIPAL    1.0
12219  99.0   0.0         SANTA CECILIA  PUESTO CABECERA MUNICIPAL    1.0
12223  99.0   0.0       VEREDA NAZARETH  PUESTO CABECERA MUNICIPAL    1.0
12255  99.0   5.0            TRES MATAS           BERLIN CONSULADO    2.0
12504  75.0   0.0  VALENCIA - CONSULADO                          0    8.0

            Sergio Fajardo        Federico Gutiérrez        Gustavo Petro  \
      other           self  other               self  other          self
12211  14.0            2.0   56.0                9.0  526.0           9.0
12219   8.0            2.0   19.0               23.0  311.0           2.0
12223  20.0            0.0   38.0               10.0  161.0           2.0
12255   6.0            4.0  411.0               16.0  257.0         106.0
12504   0.0            4.0    0.0               29.0    0.0          14.0

              John Milton Rodríguez
        other                  self other
12211   255.0                   1.0  61.0
12219   174.0                   4.0  13.0
12223   951.0                   0.0  16.0
12255  1497.0                   2.0   3.0
12504     0.0                   NaN   NaN

In [529]:
dif[dif[('COD_DANE',  'self')]==np.nan].sum()

COD_DANE                self     0.0
                        other    0.0
Departamento            self     0.0
                        other    0.0
Municipio               self     0.0
                        other    0.0
Zona                    self     0.0
                        other    0.0
Puesto                  self     0.0
                        other    0.0
# Mesa                  self     0.0
                        other    0.0
Sergio Fajardo          self     0.0
                        other    0.0
Federico Gutiérrez      self     0.0
                        other    0.0
Gustavo Petro           self     0.0
                        other    0.0
John Milton Rodríguez   self     0.0
                        other    0.0
Luis Pérez              self     0.0
                        other    0.0
Rodolfo Hernández       self     0.0
                        other    0.0
Enrique Gómez           self     0.0
                        other    0.0
Ingrid Betancourt       self     0.0
                        other    0.0
Tarjetones No Marcados  self     0.0
                        other    0.0
Votos en blanco         self     0.0
                        other    0.0
Votos nulos             self     0.0
                        other    0.0
dtype: float64

# Análisis Bogotá

In [147]:
censo_electoral[censo_electoral["municipio"]=="BOGOTA. D.C."]["comuna"].value_counts()

08LOCALIDAD  8 KENNEDY              102
11LOCALIDAD 11 SUBA                  98
10LOCALIDAD 10 ENGATIVA              81
19LOCALIDAD 19 CIUDAD BOLIVAR        67
07LOCALIDAD 7 BOSA                   67
18LOCALIDAD 18 RAFAEL URIBE URIB     56
04LOCALIDAD 4 SAN CRISTOBAL          53
01LOCALIDAD 1 USAQUEN                49
16LOCALIDAD 16 PUENTE ARANDA         44
09LOCALIDAD 9 FONTIBON               41
05LOCALIDAD 5 USME                   41
13LOCALIDAD 13 TEUSAQUILLO           32
06LOCALIDAD 6 TUNJUELITO             31
12LOCALIDAD 12 BARRIOS UNIDOS        31
02LOCALIDAD 2 CHAPINERO              28
03LOCALIDAD 3 SANTA FE               23
15LOCALIDAD 15 ANTONIO NARIÑO        20
14LOCALIDAD 14 MARTIRES              18
17LOCALIDAD 17 CANDELARIA             9
20LOCALIDAD 20 SUMAPAZ                5
Name: comuna, dtype: int64

In [308]:
censo_electoral[censo_electoral["municipio"]=="BOGOTA. D.C."]["total"].sum()

5967518

In [161]:
censo_electoral[censo_electoral["municipio"]=="BOGOTA. D.C."]["total"].sum()
#en página a la fecha 2022 bogotá: 5.935.722
#(en página a la fecha 2022 colombia: 39002239) - (total censo base: 38819901) = 182.338
censo_electoral[censo_electoral["dd"]!="TOTAL"]["total"].sum()

38819901

In [108]:
#print(list(primera_vuelta.Departamento))

In [109]:
bogota = primera_vuelta[primera_vuelta["Municipio"]=="BOGOTA. D.C."]
print(bogota["Puesto"].value_counts().head(30)) #ENGATIVA

PUESTO CENSO(FERIA EXPOSICION)    282
PARQUE FUNDACIONAL DE SUBA         86
UNICENTRO                          82
USAQUÉN                            76
BOSA                               71
FONTIBON                           64
SERVITA                            63
PATIO BONITO                       59
CHICO NORTE                        59
LA LIBERTAD                        59
CENTRO COMERCIAL TINTAL PLAZA      58
EL RINCON                          57
HAYUELOS CENTRO COMERCIAL          55
ENGATIVA                           55
CANDELARIA LA NUEVA                54
LOS CEDRITOS 151                   54
CENTRO COMERCIAL EL EDEN           53
ROMA                               52
NIZA CENTRO COMERCIAL NIZA         52
BOCHICA                            52
GRAN PLAZA EL ENSUEÑO              51
GALICIA                            51
LA VICTORIA A                      51
LA ESTANCIA                        51
CC PARQUE LA COLINA                51
SAN FRANCISCO                      50
JAIRO ANIBAL NIÑO                  50
COLEGIO HIJAS DE CRISTO REY        49
CENTRO COMERCIAL BULEVAR NIZA      49
ISMAEL PERDOMO                     48
Name: Puesto, dtype: int64

In [ ]:
bogota["Gustavo Petro"].sum()

In [122]:
bogota.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14935 entries, 27602 to 42536
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   COD_DANE                14935 non-null  object
 1   Departamento            14935 non-null  object
 2   Municipio               14935 non-null  object
 3   Zona                    14935 non-null  int64
 4   # Puesto                14935 non-null  object
 5   Puesto                  14935 non-null  object
 6   # Mesa                  14935 non-null  int64
 7   Sergio Fajardo          14935 non-null  int64
 8   Federico Gutiérrez      14935 non-null  int64
 9   Gustavo Petro           14935 non-null  int64
 10  John Milton Rodríguez   14935 non-null  int64
 11  Luis Pérez              14935 non-null  int64
 12  Rodolfo Hernández       14935 non-null  int64
 13  Enrique Gómez           14935 non-null  int64
 14  Ingrid Betancourt       14935 non-null  int64
 15  Tarjetones No Marcados  14935 non-null  int64
 16  Votos en blanco         14935 non-null  int64
 17  Votos nulos             14935 non-null  int64
dtypes: int64(13), object(5)
memory usage: 2.2+ MB

In [162]:
print(censo_electoral[(censo_electoral["comuna"]) == "10LOCALIDAD 10 ENGATIVA"]["total"].sum())
print(bogota[(bogota["Zona"]) == 10]["Gustavo Petro"].sum())
print((bogota[(bogota["Zona"]) == 10]["Gustavo Petro"].sum()/
       censo_electoral[(censo_electoral["comuna"]) == "10LOCALIDAD 10 ENGATIVA"]["total"].sum())*100)
print(censo_electoral[(censo_electoral["comuna"]) == "09LOCALIDAD 9 FONTIBON"]["total"].sum())
print(bogota[(bogota["Zona"]) == 9]["Gustavo Petro"].sum())
print((bogota[(bogota["Zona"]) == 9]["Gustavo Petro"].sum()/
       censo_electoral[(censo_electoral["comuna"]) == "09LOCALIDAD 9 FONTIBON"]["total"].sum())*100)

585572
182714
31.2026531323219
270622
81143
29.98388896689848

In [375]:
engativa = bogota[bogota["Zona"] == 10]

In [376]:
engativa.head() #Rodolfo Hernández

,COD_DANE,Departamento,Municipio,Zona,# Puesto,Puesto,# Mesa,Sergio Fajardo,Federico Gutiérrez,Gustavo Petro,John Milton Rodríguez,Luis Pérez,Rodolfo Hernández,Enrique Gómez,Ingrid Betancourt,Tarjetones No Marcados,Votos en blanco,Votos nulos
28710,11001,BOGOTA D.C.,BOGOTA. D.C.,10,1,BOYACA,1,18,62,52,2,0,67,0,0,0,2,0
28711,11001,BOGOTA D.C.,BOGOTA. D.C.,10,1,BOYACA,10,27,86,69,13,0,52,2,0,3,7,0
28712,11001,BOGOTA D.C.,BOGOTA. D.C.,10,1,BOYACA,11,26,73,85,15,0,58,0,0,1,6,2
28713,11001,BOGOTA D.C.,BOGOTA. D.C.,10,1,BOYACA,12,16,39,78,12,0,65,2,0,0,9,7
28714,11001,BOGOTA D.C.,BOGOTA. D.C.,10,1,BOYACA,13,17,22,38,7,0,51,3,0,0,4,7

In [89]:
reporte.index

Int64Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
            18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
            35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
            52, 53, 54, 55],
           dtype='int64', name='# Mesa')

In [379]:
reporte = engativa.groupby("# Mesa").sum()  # ""
reporte= reporte.iloc[:, [3,2,6,10]]
reporte["suma"] = reporte["Gustavo Petro"] + reporte["Federico Gutiérrez"]+reporte["Rodolfo Hernández"]+reporte["Votos en blanco"]
reporte.iloc[54] = np.sum(reporte[["Gustavo Petro", "Federico Gutiérrez", "Rodolfo Hernández","Votos en blanco", "suma"]])

In [380]:
reporte

,Gustavo Petro,Federico Gutiérrez,Rodolfo Hernández,Votos en blanco,suma
# Mesa,,,,,
1,7630,6451,6218,322,20621
2,7877,5787,5441,379,19484
3,6920,5336,4998,348,17602
4,6993,4807,4466,348,16614
5,6280,4691,4163,394,15528
6,5610,4264,3993,330,14197
7,5277,4105,3992,304,13678
8,5157,3808,3732,363,13060
9,5250,3498,3495,299,12542
10,5275,3521,3541,324,12661
11,5720,3179,3470,366,12735
12,5555,2965,3418,345,12283
13,5593,2501,3028,330,11452
14,5495,2313,3140,303,11251
15,5477,2169,3077,315,11038
16,5299,1970,2871,288,10428
17,5191,1895,2780,328,10194
18,4790,1897,2743,259,9689
19,4880,1503,2422,254,9059
20,4920,1368,2242,232,8762
21,4924,1274,2209,215,8622
22,4947,1186,2194,263,8590
23,4786,937,1904,210,7837
24,4462,940,1773,192,7367
25,4539,741,1745,209,7234
26,4288,781,1646,170,6885
27,4130,775,1670,177,6752
28,3629,716,1405,176,5926
29,3309,575,1254,159,5297
30,3082,513,1214,122,4931
31,2860,459,1044,115,4478
32,2629,360,895,116,4000
33,2390,326,803,123,3642
34,2124,314,733,86,3257
35,1926,247,642,75,2890
36,1801,259,621,63,2744
37,1628,269,617,76,2590
38,1588,224,496,69,2377
39,1380,166,492,59,2097
40,1087,129,345,40,1601
41,813,91,282,30,1216
42,800,108,296,27,1231
43,762,97,282,27,1168
44,813,102,214,21,1150
45,543,61,149,18,771
46,373,48,97,17,535
47,313,34,88,10,445
48,322,36,124,9,491
49,320,40,119,14,493
50,312,32,137,12,493
51,254,36,92,18,400
52,128,23,52,4,207
53,82,9,32,4,127
54,109,14,40,7,170
55,182714,79964,98962,9369,371009

In [382]:
#np.sum(reporte[["Gustavo Petro", "Federico Gutiérrez", "Rodolfo Hernández"]])